build: false

image:
  - Visual Studio 2019
  - macOS
  - Ubuntu2204

platform: x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  build_script:
  - set CL=/MP # parallel build
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 16 2019" -A Win32 -DQTDIR="C:\Qt\6.5.3\msvc2019"
  - cmake --build . --config Release
-
  matrix:
    only:
      - image: macOS
  build_script:
  - mkdir build && cd build
  - cmake .. -DQTDIR="/Users/appveyor/Qt/6.6.1/macos"
  - cmake --build . -- -j4
-
  matrix:
    only:
      - image: Ubuntu2204
  build_script:
  - mkdir build && cd build
  - cmake .. -DQTDIR="/home/appveyor/Qt/6.7.2/gcc_64"
  - cmake --build . -- -j4
